# Generated by Django 6.0.2 on 2026-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pledge_text', models.TextField(default='I pledge to keep my environment clean.')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
