# Generated by Django 6.0.2 on 2026-02-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='city',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pledge',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pledge',
            name='designation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pledge',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pledge',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pledge',
            name='emp_code',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pledge',
            name='place',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pledge',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
