# Generated by Django 6.0.2 on 2026-02-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
