# Generated by Django 6.0.2 on 2026-03-02 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0004_admin_mobile_admin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='pledgeCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledgeName', models.CharField(max_length=500)),
                ('logo1', models.ImageField(blank=True, upload_to='logos/')),
                ('logo2', models.ImageField(blank=True, upload_to='logos/')),
                ('logo3', models.ImageField(blank=True, upload_to='logos/')),
                ('pledgeText', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
