# Generated by Django 6.0.2 on 2026-03-02 20:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0005_pledgecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgecreate',
            name='pledgeName',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
