# Generated by Django 6.0.2 on 2026-03-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0006_alter_pledgecreate_pledgename'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgecreate',
            name='checkboxText',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='pledgecreate',
            name='language',
            field=models.CharField(choices=[('TA', 'Tamil'), ('EN', 'English'), ('HI', 'Hindi')], default='EN', max_length=2),
        ),
    ]
