# Generated by Django 6.0.2 on 2026-03-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0007_pledgecreate_checkboxtext_pledgecreate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pledgeLanguage',
            field=models.CharField(choices=[('TA', 'Tamil'), ('EN', 'English'), ('HI', 'Hindi')], default='EN', max_length=2),
        ),
    ]
