# Generated by Django 6.0.2 on 2026-03-03 00:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0008_pledge_pledgelanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pledge_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
