# Generated by Django 6.0.2 on 2026-03-05 04:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0009_alter_pledge_pledge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='englishPledgeText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='hindiPledgeText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='tamilPledgeText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
