# Generated by Django 6.0.2 on 2026-03-05 05:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0010_pledge_englishpledgetext_pledge_hindipledgetext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='englishPledgeText',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='hindiPledgeText',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='tamilPledgeText',
        ),
        migrations.AddField(
            model_name='pledgecreate',
            name='englishPledgeText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledgecreate',
            name='hindiPledgeText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledgecreate',
            name='tamilPledgeText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
