# Generated by Django 6.0.2 on 2026-03-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0011_remove_pledge_englishpledgetext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgecreate',
            name='englishPledgeText',
        ),
    ]
