# Generated by Django 6.0.2 on 2026-03-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0012_remove_pledgecreate_englishpledgetext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgecreate',
            name='language',
        ),
    ]
