# Generated by Django 6.0.2 on 2026-03-04 22:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0013_remove_pledgecreate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgecreate',
            name='hindiPledgeName',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledgecreate',
            name='tamilPledgeName',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
