# Generated by Django 6.0.2 on 2026-03-04 22:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_app', '0014_pledgecreate_hindipledgename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pledgeName',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
